### PR TITLE
Python 3.12+ compatibility - module 'ssl' has no attribute 'wrap_socket'

### PR DESCRIPTION
**Pull request by riklaunim**
ssl.wrap_socket was deprecated since Python 3.7 and remove in 3.12 so for it to work with 3.12 SSLContext.wrap_socket has to be used.

https://pradyunsg-cpython-lutra-testing.readthedocs.io/en/latest/whatsnew/3.12.html

Tested for my use case and it seems to be working fine, although did not test with self.key_file/self.cert_file set which were undefined (and None in some test).

### CODE REVIEW

**Comment by hronecviktor** [comment]
:+1: For this, we need this merged ASAP too

**Comment by PeterDekkers** [comment]
@henrys-cm or anyone at CM, could you please review this?

This Python library doesn't work with Python 3.12+, which I assume is reasonably important.

**Comment by mikemanger** [comment]
I've tried emailing the support to try and get some action on this.
One thing that is missing from this PR is it would be good to update tox to test against Python 3.11 and 3.12.

**Comment by riklaunim** [comment]
> I've tried emailing the support to hopefully get some action on this. One thing that is missing from this PR is it would be good to update tox to test against Python 3.11 and 3.12.

That can be added, although someone with knowledge of the codebase has to look at this. Like those `hasattr` I had to use were quite unexpected.

File: lib/createsend/utils.py [hunk 1]
```diff
@@ -101,12 +101,21 @@ def connect(self):
...
 
-        self.sock = ssl.wrap_socket(
-            sock,
-            self.key_file,
-            self.cert_file,
-            cert_reqs=ssl.CERT_REQUIRED,
-            ca_certs=cert_path)
+        # for >= py3.7, mandatory since 3.12
+        if hasattr(ssl.SSLContext, 'wrap_socket'):
+            context = ssl.SSLContext()
```
Comment (russella-acm) [inline lib/createsend/utils.py:106]: Hi @riklaunim - thank you for putting this PR forward - we really appreciate it and I can see it is looking good and working with higher versions in my testing so far.

Our apologies this only came to attention recently. We are eager to get this moving forward for the Python community, merging it in and updating the package so that it can be used with higher versions of Python as you've rightly pointed out.

In some testing, I noticed with Python 2.7.18, with this specific line it was causing this issue:

```
    context = ssl.SSLContext()
TypeError: __new__() takes at least 2 arguments (1 given)
```

I was wondering if it would be ok to replace this line with:
```
context = ssl.SSLContext(ssl.PROTOCOL_TLS)
```

I found by doing that I was able to get around the TypeError. I am by no means an experienced Python developer and this may not be the right thing to do. I am very open to your thoughts and feedback about that in a bid to move this forward as quickly as possible. Merging in your fix is a top priority for us at the moment.

Comment (riklaunim) [reply lib/createsend/utils.py:106]: Python 2 is long gone (same as Python 3.8 and lower) so you may look at dropping the support for it. And yes, it would have to be replaced to
`context = ssl.SSLContext(ssl.PROTOCOL_TLS)`, should be fine.

Comment (russella-acm) [reply lib/createsend/utils.py:106]: Excellent - thank you for the feedback @riklaunim - we will most likely drop supporting older versions of Python and update the version of the createsend-python package with your changes included.
